// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250224114239_FixVillaNumberTable")]
    partial class FixVillaNumberTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreateDate = new DateTime(2025, 2, 20, 10, 25, 44, 101, DateTimeKind.Local).AddTicks(3216),
                            Details = "Situated in Poissy, a small commune outside of Paris, Villa Savoye is one of the most significant contributions to modern architecture in the 20th century. Completed in 1929, Le Corbusier's masterpiece is a modern take on a French country house that celebrates and reacts to the new machine age.",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.myluxoria.com%2Fpl%2Fwille-pula%2Fvilla-vestibul&psig=AOvVaw3NHQ8dlOMqLJ8h69c1lHCe&ust=1740129122224000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKDc66P00YsDFQAAAAAdAAAAABAE",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreateDate = new DateTime(2025, 2, 20, 10, 25, 44, 105, DateTimeKind.Local).AddTicks(6489),
                            Details = "Situated in Poissy, a small commune outside of Paris, Villa Savoye is one of the most significant contributions to modern architecture in the 20th century. Completed in 1929, Le Corbusier's masterpiece is a modern take on a French country house that celebrates and reacts to the new machine age.",
                            ImageUrl = "https://unique-residence.com/wp-content/uploads/2020/05/WILLA-E%CC%81LE%CC%81GANT_mirror-1.jpg",
                            Name = "Diamond Pool Villa",
                            Occupancy = 6,
                            Rate = 350.0,
                            Sqft = 700,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreateDate = new DateTime(2025, 2, 20, 10, 25, 44, 105, DateTimeKind.Local).AddTicks(6524),
                            Details = "Situated in Poissy, a small commune outside of Paris, Villa Savoye is one of the most significant contributions to modern architecture in the 20th century. Completed in 1929, Le Corbusier's masterpiece is a modern take on a French country house that celebrates and reacts to the new machine age.",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.behance.net%2Fgallery%2F93248823%2FElegant-Modern-Villa%3Flocale%3Dpl_PL&psig=AOvVaw3NHQ8dlOMqLJ8h69c1lHCe&ust=1740129122224000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKDc66P00YsDFQAAAAAdAAAAABAd",
                            Name = "Diamond Villa",
                            Occupancy = 4,
                            Rate = 250.0,
                            Sqft = 800,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreateDate = new DateTime(2025, 2, 20, 10, 25, 44, 105, DateTimeKind.Local).AddTicks(6529),
                            Details = "Situated in Poissy, a small commune outside of Paris, Villa Savoye is one of the most significant contributions to modern architecture in the 20th century. Completed in 1929, Le Corbusier's masterpiece is a modern take on a French country house that celebrates and reacts to the new machine age.",
                            ImageUrl = "https://www.google.com/url?sa=i&url=https%3A%2F%2Feastwest.com%2Finsights%2Fvacation-rentals%2Fwhat-is-the-difference-between-a-hotel-room-and-a-villa%2F&psig=AOvVaw3NHQ8dlOMqLJ8h69c1lHCe&ust=1740129122224000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCKDc66P00YsDFQAAAAAdAAAAABAn",
                            Name = "Premium Poll Villa",
                            Occupancy = 7,
                            Rate = 400.0,
                            Sqft = 900,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreateDate = new DateTime(2025, 2, 20, 10, 25, 44, 105, DateTimeKind.Local).AddTicks(6532),
                            Details = "Situated in Poissy, a small commune outside of Paris, Villa Savoye is one of the most significant contributions to modern architecture in the 20th century. Completed in 1929, Le Corbusier's masterpiece is a modern take on a French country house that celebrates and reacts to the new machine age.",
                            ImageUrl = "https://www.adriaticluxuryvillas.com/uploads/images/villa-di-polisane-zadar-dalmatia-1716977474706.jpg",
                            Name = "Luxury Pool Villa",
                            Occupancy = 5,
                            Rate = 300.0,
                            Sqft = 1100,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VillaNo");

                    b.ToTable("VillaNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
